### ISSUE TITLE
Application cannot be cast to Application

### ISSUE THREAD

**Issue by blofroth** [jbossdemocentral/bpms-mortgage-demo#24] opened 2016-08-21 20:07 UTC
Unexpected error encountered: [com.redhat.bpms.examples.mortgage.MortgageApplication:2 - Validate Application:11] -- com.redhat.bpms.examples.mortgage.Application cannot be cast to com.redhat.bpms.examples.mortgage.Application

Using fb650679ccf, built with docker but modified for EAP patch 6.4.8.

I was simply trying to start the process and had just entered application details in the form, and clicked submit.

Full stacktrace:
20:02:38,431 ERROR [org.guvnor.common.services.backend.exceptions.ExceptionUtilities] (http-0.0.0.0:8080-4) Exception thrown: [com.redhat.bpms.examples.mortgage.MortgageApplication:2 - Validate Application:11] -- com.redhat.bpms.examples.mortgage.Application cannot be cast to com.redhat.bpms.examples.mortgage.Application: org.jbpm.workflow.instance.WorkflowRuntimeException: [com.redhat.bpms.examples.mortgage.MortgageApplication:2 - Validate Application:11] -- com.redhat.bpms.examples.mortgage.Application cannot be cast to com.redhat.bpms.examples.mortgage.Application
	at org.jbpm.workflow.instance.impl.NodeInstanceImpl.executeAction(NodeInstanceImpl.java:206) [jbpm-flow-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.jbpm.workflow.instance.impl.ExtendedNodeInstanceImpl.triggerEvent(ExtendedNodeInstanceImpl.java:56) [jbpm-flow-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.jbpm.workflow.instance.impl.ExtendedNodeInstanceImpl.internalTrigger(ExtendedNodeInstanceImpl.java:35) [jbpm-flow-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.jbpm.workflow.instance.node.StateBasedNodeInstance.internalTrigger(StateBasedNodeInstance.java:72) [jbpm-flow-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.jbpm.workflow.instance.node.RuleSetNodeInstance.internalTrigger(RuleSetNodeInstance.java:66) [jbpm-flow-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.jbpm.workflow.instance.impl.NodeInstanceImpl.trigger(NodeInstanceImpl.java:173) [jbpm-flow-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.jbpm.workflow.instance.impl.NodeInstanceImpl.triggerNodeInstance(NodeInstanceImpl.java:366) [jbpm-flow-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.jbpm.workflow.instance.impl.NodeInstanceImpl.triggerCompleted(NodeInstanceImpl.java:325) [jbpm-flow-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.jbpm.workflow.instance.node.JoinInstance.triggerCompleted(JoinInstance.java:266) [jbpm-flow-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.jbpm.workflow.instance.node.JoinInstance.internalTrigger(JoinInstance.java:62) [jbpm-flow-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.jbpm.workflow.instance.impl.NodeInstanceImpl.trigger(NodeInstanceImpl.java:173) [jbpm-flow-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.jbpm.workflow.instance.impl.NodeInstanceImpl.triggerNodeInstance(NodeInstanceImpl.java:366) [jbpm-flow-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.jbpm.workflow.instance.impl.NodeInstanceImpl.triggerCompleted(NodeInstanceImpl.java:325) [jbpm-flow-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.jbpm.workflow.instance.node.StartNodeInstance.triggerCompleted(StartNodeInstance.java:73) [jbpm-flow-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.jbpm.workflow.instance.node.StartNodeInstance.internalTrigger(StartNodeInstance.java:44) [jbpm-flow-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.jbpm.workflow.instance.impl.NodeInstanceImpl.trigger(NodeInstanceImpl.java:173) [jbpm-flow-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.jbpm.ruleflow.instance.RuleFlowProcessInstance.internalStart(RuleFlowProcessInstance.java:35) [jbpm-flow-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.jbpm.process.instance.impl.ProcessInstanceImpl.start(ProcessInstanceImpl.java:236) [jbpm-flow-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.jbpm.workflow.instance.impl.WorkflowProcessInstanceImpl.start(WorkflowProcessInstanceImpl.java:439) [jbpm-flow-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.jbpm.process.instance.ProcessRuntimeImpl.startProcessInstance(ProcessRuntimeImpl.java:208) [jbpm-flow-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.jbpm.process.instance.ProcessRuntimeImpl.startProcessInstance(ProcessRuntimeImpl.java:217) [jbpm-flow-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.jbpm.process.instance.ProcessRuntimeImpl.startProcess(ProcessRuntimeImpl.java:225) [jbpm-flow-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.drools.core.impl.StatefulKnowledgeSessionImpl.startProcess(StatefulKnowledgeSessionImpl.java:1859) [drools-core-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.drools.core.command.runtime.process.StartCorrelatedProcessCommand.execute(StartCorrelatedProcessCommand.java:146) [drools-core-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.drools.core.command.runtime.process.StartCorrelatedProcessCommand.execute(StartCorrelatedProcessCommand.java:44) [drools-core-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.drools.core.command.impl.DefaultCommandService.execute(DefaultCommandService.java:36) [drools-core-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.drools.core.command.impl.AbstractInterceptor.executeNext(AbstractInterceptor.java:41) [drools-core-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.drools.persistence.SingleSessionCommandService$TransactionInterceptor.execute(SingleSessionCommandService.java:592) [drools-persistence-jpa-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.drools.core.command.impl.AbstractInterceptor.executeNext(AbstractInterceptor.java:41) [drools-core-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.drools.persistence.jpa.OptimisticLockRetryInterceptor.execute(OptimisticLockRetryInterceptor.java:82) [drools-persistence-jpa-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.drools.core.command.impl.AbstractInterceptor.executeNext(AbstractInterceptor.java:41) [drools-core-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.drools.persistence.jta.TransactionLockInterceptor.execute(TransactionLockInterceptor.java:73) [drools-persistence-jpa-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.drools.persistence.SingleSessionCommandService.execute(SingleSessionCommandService.java:385) [drools-persistence-jpa-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.drools.core.command.impl.CommandBasedStatefulKnowledgeSession.startProcess(CommandBasedStatefulKnowledgeSession.java:547) [drools-core-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.jbpm.kie.services.impl.ProcessServiceImpl.startProcess(ProcessServiceImpl.java:126) [jbpm-kie-services-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.jbpm.services.cdi.impl.ProcessServiceCDIImpl$Proxy$_$$_WeldClientProxy.startProcess(ProcessServiceCDIImpl$Proxy$_$$_WeldClientProxy.java) [jbpm-services-cdi-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.jbpm.console.ng.bd.backend.server.KieSessionEntryPointImpl.startProcess(KieSessionEntryPointImpl.java:78) [jbpm-console-ng-business-domain-backend-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.jbpm.console.ng.bd.backend.server.KieSessionEntryPointImpl$Proxy$_$$_WeldClientProxy.startProcess(KieSessionEntryPointImpl$Proxy$_$$_WeldClientProxy.java) [jbpm-console-ng-business-domain-backend-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.jbpm.console.ng.ht.forms.backend.server.FormModelerProcessStarterEntryPointImpl.startProcessFromRenderContext(FormModelerProcessStarterEntryPointImpl.java:50) [jbpm-console-ng-human-tasks-forms-modeler-backend-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.jbpm.console.ng.ht.forms.backend.server.FormModelerProcessStarterEntryPointImpl$Proxy$_$$_WeldClientProxy.startProcessFromRenderContext(FormModelerProcessStarterEntryPointImpl$Proxy$_$$_WeldClientProxy.java) [jbpm-console-ng-human-tasks-forms-modeler-backend-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_71]
	at java.lang.reflect.Method.invoke(Method.java:497) [rt.jar:1.8.0_71]
	at org.jboss.errai.bus.server.io.AbstractRPCMethodCallback.invokeMethodFromMessage(AbstractRPCMethodCallback.java:48) [errai-bus-3.2.3.Final-redhat-1.jar:3.2.3.Final-redhat-1]
	at org.jboss.errai.bus.server.io.ValueReplyRPCEndpointCallback.callback(ValueReplyRPCEndpointCallback.java:22) [errai-bus-3.2.3.Final-redhat-1.jar:3.2.3.Final-redhat-1]
	at org.jboss.errai.bus.server.io.RemoteServiceCallback.callback(RemoteServiceCallback.java:54) [errai-bus-3.2.3.Final-redhat-1.jar:3.2.3.Final-redhat-1]
	at org.jboss.errai.cdi.server.CDIExtensionPoints$2.callback(CDIExtensionPoints.java:396) [errai-weld-integration-3.0.6.Final-redhat-1.jar:3.0.6.Final-redhat-1]
	at org.jboss.errai.bus.server.DeliveryPlan.deliver(DeliveryPlan.java:47) [errai-bus-3.2.3.Final-redhat-1.jar:3.2.3.Final-redhat-1]
	at org.jboss.errai.bus.server.ServerMessageBusImpl.sendGlobal(ServerMessageBusImpl.java:296) [errai-bus-3.2.3.Final-redhat-1.jar:3.2.3.Final-redhat-1]
	at org.jboss.errai.bus.server.SimpleDispatcher.dispatchGlobal(SimpleDispatcher.java:46) [errai-bus-3.2.3.Final-redhat-1.jar:3.2.3.Final-redhat-1]
	at org.jboss.errai.bus.server.service.ErraiServiceImpl.store(ErraiServiceImpl.java:97) [errai-bus-3.2.3.Final-redhat-1.jar:3.2.3.Final-redhat-1]
	at org.jboss.errai.bus.server.service.ErraiServiceImpl.store(ErraiServiceImpl.java:114) [errai-bus-3.2.3.Final-redhat-1.jar:3.2.3.Final-redhat-1]
	at org.jboss.errai.bus.server.servlet.DefaultBlockingServlet.doPost(DefaultBlockingServlet.java:142) [errai-bus-3.2.3.Final-redhat-1.jar:3.2.3.Final-redhat-1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:754) [jboss-servlet-api_3.0_spec-1.0.2.Final-redhat-2.jar:1.0.2.Final-redhat-2]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.2.Final-redhat-2.jar:1.0.2.Final-redhat-2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.5.16.Final-redhat-1.jar:7.5.16.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.16.Final-redhat-1.jar:7.5.16.Final-redhat-1]
	at org.uberfire.ext.security.server.SecureHeadersFilter.doFilter(SecureHeadersFilter.java:69) [uberfire-servlet-security-0.8.0.Final-redhat-3.jar:0.8.0.Final-redhat-3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.5.16.Final-redhat-1.jar:7.5.16.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.16.Final-redhat-1.jar:7.5.16.Final-redhat-1]
	at org.uberfire.ext.security.server.SecurityIntegrationFilter.doFilter(SecurityIntegrationFilter.java:61) [uberfire-servlet-security-0.8.0.Final-redhat-3.jar:0.8.0.Final-redhat-3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.5.16.Final-redhat-1.jar:7.5.16.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.16.Final-redhat-1.jar:7.5.16.Final-redhat-1]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:231) [jbossweb-7.5.16.Final-redhat-1.jar:7.5.16.Final-redhat-1]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) [jbossweb-7.5.16.Final-redhat-1.jar:7.5.16.Final-redhat-1]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:512) [jbossweb-7.5.16.Final-redhat-1.jar:7.5.16.Final-redhat-1]
	at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.5.8.Final-redhat-2.jar:7.5.8.Final-redhat-2]
	at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.5.8.Final-redhat-2.jar:7.5.8.Final-redhat-2]
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.5.8.Final-redhat-2.jar:7.5.8.Final-redhat-2]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:150) [jbossweb-7.5.16.Final-redhat-1.jar:7.5.16.Final-redhat-1]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.5.16.Final-redhat-1.jar:7.5.16.Final-redhat-1]
	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:419) [jbossweb-7.5.16.Final-redhat-1.jar:7.5.16.Final-redhat-1]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.5.16.Final-redhat-1.jar:7.5.16.Final-redhat-1]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344) [jbossweb-7.5.16.Final-redhat-1.jar:7.5.16.Final-redhat-1]
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:854) [jbossweb-7.5.16.Final-redhat-1.jar:7.5.16.Final-redhat-1]
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:654) [jbossweb-7.5.16.Final-redhat-1.jar:7.5.16.Final-redhat-1]
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:926) [jbossweb-7.5.16.Final-redhat-1.jar:7.5.16.Final-redhat-1]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_71]
Caused by: java.lang.ClassCastException: com.redhat.bpms.examples.mortgage.Application cannot be cast to com.redhat.bpms.examples.mortgage.Application
	at com.redhat.bpms.examples.mortgage.Process_com$u46$redhat$u46$bpms$u46$examples$u46$mortgage$u46$MortgageApplication1671723260Action14Invoker.execute(Process_com$u46$redhat$u46$bpms$u46$examples$u46$mortgage$u46$MortgageApplication1671723260Action14Invoker.java:12)
	at org.jbpm.workflow.instance.impl.NodeInstanceImpl.executeAction(NodeInstanceImpl.java:200) [jbpm-flow-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	... 78 more

**Comment by DuncanDoyle** [comment] 2016-08-22 08:52
Can you provide me with the values you submitted in the form when you started the process instance? I'm unable to reproduce this in my environment (Docker, JBoss EAP 6.4.8 & JBoss BPMSuite 6.3.0.GA).

**Comment by blofroth** [comment] 2016-08-22 09:07
I will try to reproduce it when I get back home today.

I tried booting up the EAP/BPM fresh this morning and the it worked with
the values provided in the quick guide pdf.

Trying to recall what exactly I had been doing when I saw the error. I was
clicking around the tasks view, claiming and releasing tasks. I remember
clicking the complete button but nothing happened. (Not even an error)

I realize that is a vague description ;)

I will try to come up with more precise steps to reproduce this evening.

BR Björn

Den 22 aug. 2016 10:52 AM skrev "DuncanDoyle" <notifications@github.com>:

**Comment by DuncanDoyle** [comment] 2016-09-02 05:01
Any update on this one?

**Comment by DuncanDoyle** [comment] 2016-09-03 05:36
No problem. I'll close the issue. Please re-open or create a new issue when happen to see the problem again.

**Comment by DuncanDoyle** [comment] 2016-09-03 05:36
Can't reproduce.

**Closed by DuncanDoyle** 2016-09-03 05:36 UTC
